name: nasa_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1

  flutter_foreground_task: ^9.1.0
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.0
  flutter_reactive_ble: ^5.3.1
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:  
  uses-material-design: true
  assets:
    - assets/.env
    - assets/sounds/sound1.wav
    - assets/logo/nasa_logo.png
    - assets/key/
